site_name: Notion Recurring Tasks Documentation

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

theme:
  name: "material"
  palette:
    scheme: slate
    primary: black
    accent: purple
  features:
    - navigation.top
    - navigation.sections
    - navigation.indexes
    - navigation.tracking
    - toc.follow

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            separate_signature: true
            show_signature_annotations: true
            merge_init_into_class: true
            docstring_options:
              returns_named_value: false
              ignore_init_summary: true
  - autorefs
  - gen-files:
      scripts:
      - scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md

markdown_extensions:
  - footnotes

nav:
  - Home: index.md
  - Tutorials:
    - tutorial/index.md
    - Getting Started: tutorial/getting-started.md
  - How-to-Guides:
    - how-to-guide/index.md
  - Code References: reference/
  - Explanations:
    - explanation/index.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Theeoi/notion-recurring-tasks
  generator: false

copyright: Copyright &copy; 2024 Theodor Blom