site_name: Notion Recurring Tasks Documentation

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

theme:
  name: "material"
  logo: assets/icon/white.png
  favicon: assets/icon/black.png
  palette:
    scheme: slate
    primary: black
    accent: purple
  features:
    - navigation.top
    - navigation.sections
    - navigation.indexes
    - navigation.tracking
    - toc.follow

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            separate_signature: true
            show_signature_annotations: true
            merge_init_into_class: true
            docstring_options:
              returns_named_value: false
              ignore_init_summary: true
  - autorefs
  - gen-files:
      scripts:
      - scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md

markdown_extensions:
  - footnotes
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Demonstration: demonstration.md
  - Tutorials:
    - tutorial/index.md
    - Getting Started:
      - tutorial/getting-started/index.md
      - Alternatives to Downloading the Finished Executable: tutorial/getting-started/alternatives-to-download.md
    - Automatically Running the Software: tutorial/automating-the-software.md
  - How-to-Guides:
    - how-to-guide/index.md
  - Code References: reference/
  - Explanations:
    - explanation/index.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Theeoi/notion-recurring-tasks
  generator: false

copyright: Copyright &copy; 2024 Theodor Blom