name: Deploy to VPS

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: [ubuntu-20.04]
        steps:
            - uses: actions/checkout@v1

            - name: Copy repo content to VPS
              uses: appleboy/scp-action@master
              with: 
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.SSHKEY }}
                source: ".,!tests,!.git,!.vscode"
                target: "/home/theodorb/notion-recurring-tasks/"

            - name: Install dependancies
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.SSHKEY }}
                script: |
                    cd /home/theodorb/notion-recurring-tasks
                    . .venv/bin/activate
                    python -m pip install --upgrade pip setuptools wheel
                    pip install .